### ISSUE TITLE
第一章：样本量对研究结果的影响

### ISSUE THREAD

**Issue by smileszh** [azanghai/R4Starter#4]
“在比较“简单”和“复杂”条件的情况下，如果我们从同一总体中抽取小样本（例如，N=20），则样本之间存在差异的可能性更高，这些差异仅仅是由于随机偶然。这可能会导致我们得出两种条件之间存在实际差异的结论，而实际上并不存在”

第一句话没明白啥意思！！！

**Comment by azanghai** [comment]
这里想描述的是样本数量不足的情况下开展比较可能的到错误的结论。我会尝试修改
